#file: noinspection SpringBootApplicationYaml# -> this is for suppressing `config-server configuration` warning
server:
  port: 9999

spring:
  application:
    name: API-GATEWAY
---

#config-server configuration
spring:
  config:
    import: optional:configserver:http://localhost:9296/
---

#api-gateway configuration
# configuration for gateway has been moved to java class -> GatewayConfig
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: AUTHENTICATION-SERVICE
#          uri: lb://AUTHENTICATION-SERVICE
#          predicates:
#            - Path=/api/v1/auth/**
---

spring:
  main:
    web-application-type: reactive
---
